// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Color = "Black & Tan",
                            Name = "Beethoven",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Color = "Orange",
                            Name = "Garfield",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Color = "Tan",
                            Name = "Marley",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Color = "Brindle",
                            Name = "Fido",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            Color = "Grey",
                            Name = "Smokey",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Color = "Black",
                            Name = "Cujo",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 2,
                            Color = "Calico",
                            Name = "Cali",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 6,
                            Color = "Golden",
                            Name = "Bud",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 1,
                            Color = "Red",
                            Name = "Clifford",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 4,
                            Color = "Tuxedo",
                            Name = "Tom",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
